DEV-40 Placeholder course's area does not reflect in degree progress
uCredit-Dev/ucredit_frontend_typescript pull request #388
Opened 2022-10-24 05:22 UTC by josephined21

### Description
Placeholder course's area does not reflect in degree progress. For example, if the user creates a placeholder course that is in the Humanities (H) area, that course is not accounted for in the Humanities and Social Sciences degree progress.

### Implementation
The implementation is in DistributionBarsJSX.tsx. Previously, in updateReqs, courseObj was null for placeholder courses; updateReqs did not check distributions for placeholder courses. Now, if courseObj is null, courseObj is created with placeholder course data. 

### Testing
Tested locally.

2022-10-24 05:42 UTC, mattliu-mygit requested changes
There seems to be merge conflicts. Lets resolve those first? ^.^

2022-10-24 06:00 UTC, mattliu-mygit requested changes
Can we have a case that satisfies any random title or number the user may put? Since we would want the course to count even if the course number is empty, or called "some h course"

2022-11-08 15:23 UTC, aryamanshodhan approved these changes
Looks good to me! great work Josephine!

2022-11-08 18:12 UTC, mattliu-mygit approved these changes

2022-11-08 20:52 UTC, merged