Dev 39 - Placeholder course does not save department or tag
uCredit-Dev/ucredit_frontend_typescript pull request #438
Opened 2023-01-27 15:06 UTC by Byuljapcho

**Description**
When a user creates a custom course and adds it to the plan, the department and tag values would not save and show up as "none" when the user opens up the customized course again. 

**Implementation**
In the CourseDisplayPopup.tsx, I changed the department value in the to-be-dispatched new placeholderCourse object from "none" to user-changed department value. I also added the department value to the json body request so that the backend also gets the updated values. In the CourseDisplay.tsx, I added code to update the user-changed tag values in the backend. Finally, in Placeholder.tsx, I added code to set the tag value if it exists and also display the retrieved tag value.  

**Testing**
Tested locally.
<img width="1183" alt="Screen Shot 2023-01-27 at 9 48 00 AM" src="https://user-images.githubusercontent.com/89854941/215115132-6b85b6ca-c0a5-4c1e-8878-3b722c30705d.png">

2023-02-02 22:34 UTC, mattliu-mygit requested changes
Please fix prettier issues.

2023-02-02 22:34 UTC, mpark63 requested changes

2023-02-02 22:34 UTC, mpark63 commented on lib/components/popups/course-search/search-results/Placeholder.tsx
> +      console.log(inspCopy, 3);
remove console.log

2023-02-11 05:00 UTC, mattliu-mygit approved these changes
Lgtm!

2023-02-12 19:34 UTC, uCredit-Dev commented on lib/components/popups/course-search/search-results/Placeholder.tsx
> +      console.log(inspCopy, 3);
done

2023-02-14 04:38 UTC, josephined21 approved these changes

2023-02-14 04:44 UTC, josephined21 requested changes
for line 146 in placeholder.tsx, can you delete the comment?

2023-02-17 01:07 UTC, mpark63 approved these changes

2023-02-17 01:22 UTC, merged