IN-19 Set up Amplitude TypeScript SDK for Data Analytics
uCredit-Dev/ucredit_frontend_typescript pull request #449
Opened 2023-03-04 06:55 UTC by josephined21

### Description
We want to use Data Analytics to track information like how many unique users does uCredit have, how much time do users spend using uCredit, what features are the most vs the least commonly used, etc. This is important for UI/UX team's research!

### Implementation
Implemented Data Analytics tracking with Amplitude's TypeScript SDK. Initialize User ID upon login in [[...token]].tsx. Track events (user actions) such as Deleted Course, Changed Majors, JHU User Login. Worked with Sean to categorize these events (e.g. Edit Course, Edit Plan Info, Login). See [Sean's Notion](https://www.notion.so/Compile-list-of-events-for-web-app-fa32993ebeaf4e1fbc31be06a12a91f0) for the full list of events. Track user properties Affiliation (Student, Staff), Grade (Freshman, Sophomore, ...), and Number of Plans with Amplitude Identify API. 

Log in to Amplitude with uCredit Dev account to view [Data](https://data.amplitude.com/ucredit) and [Analytics](https://analytics.amplitude.com/ucredit/home). I set up 'Sample Dashboard' with charts to display uCredit's user composition by affiliation, grade, and number of plans (these are the three user properties currently being tracked). I also copied four of Amplitude's default dashboard templates -- User Activity, Session Engagement, Feature Adoption, and Conversion Report. I anticipate that these dashboards are temporary and that Sean will want to customize these. 

### Testing
Created a Test Project on Amplitude. Tested locally.

### Action Items
Ask uCredit team to test. Set up Development Project and Production Project.

2023-03-04 18:46 UTC, mattliu-mygit approved these changes
Looks good!

2023-03-04 18:47 UTC, mattliu-mygit requested changes
Can you double check prettier issues pls :3?

2023-03-04 18:53 UTC, mattliu-mygit approved these changes

2023-03-05 00:10 UTC, aryamanshodhan approved these changes
Looks good to me!

2023-03-06 05:11 UTC, merged