Dev-142: remove old majors and change the names of new majors
uCredit-Dev/ucredit_frontend_typescript pull request #464
Opened 2023-03-22 03:42 UTC by RosaGao

2023-03-26 20:38 UTC, mpark63 requested changes
ok looks good to me, did you try testing yet? 

if not, please run this script with dev database and test the DEV-142 branches locally. Nothing should break hopefully.

Also please summarize changes you made to majors.tsx!

2023-03-26 20:38 UTC, mpark63 commented on lib/resources/majors.tsx
> +const baCS_New: Major = {
feel free to just name the var baCS

2023-03-26 20:38 UTC, mpark63 commented on lib/resources/majors.tsx
> +            '^OR^EN.601.229[C]^OR^EN.601.230[C]^OR^EN.601.433[C]^OR^EN.601.231[C]',
awesome awesome

2023-03-27 02:03 UTC, josephined21 approved these changes
looks good! :D

2023-03-27 02:03 UTC, mpark63 approved these changes
lgtm!

2023-03-27 02:12 UTC, josephined21 approved these changes
pog!

2023-03-27 02:19 UTC, merged